on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths-ignore:
      - "**/*.md"

name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "pacman --noconfirm -Syu base-devel cmake gcc git make xorg-server-xephyr"

      - name: Compile
        run: "mkdir build && cd build && cmake .. && cmake --build . --config Release"
